### ISSUE TITLE
Consider using argparse for interface name

### ISSUE THREAD

**Issue by thegoldenmule** [Bradart/firestick-kodi-installer#4]
Tutorial [here](https://docs.python.org/2/howto/argparse.html).

Basically, it'd be nice to be able to specify the interface from command line. You could default it to 'eth0' (or whatever you use most often) then override it like:

`python firestick.py -i eth1`

**Comment by ghost** [comment]
Yeah I debated doing this, because I want to have the end user edit the script as little as possible. I just failed to add this in. If Bradart doesn't get to it, I will add it in. My default NIC is currently configured in it. lol

**Comment by bradganley** [comment]
I probably won't get to it because I don't actually understand what on earth you are talking about at this moment.

**Comment by ghost** [comment]
LOL so in the readme for the auto install to work you have to edit in your NIC. He is suggesting we give the user a way to pass it via arguments instead of actually editing the script itself. Makes sense, good thing to add. 

It is also lacking any error handling which I will poke at as I get time. 👍

**Comment by bradganley** [comment]
Cool. I'll do the kids table stuff and try to keep up.

**Comment by ghost** [comment]
Dude, I'm here to help you learn. So if you have any questions just hit me up. If you want me to stop pushing commits I can as well. Just am trying to be helpful @Bradart. Just let me know!

**Comment by bradganley** [comment]
Oh no don't take that the wrong way. I'm super stoked to actually have real world code to look at. I just feel useless haha. I'm loving this, but my knowledge is small

**Comment by thegoldenmule** [comment]
I think you should try to add the argparse stuff, @Bradart! We could do it for you but what's the fun in that.

**Comment by ghost** [comment]
Looks like argparse requires python 2.7+, so while we can use it, I think using getopt maybe the better move for more compatibility. Thoughts?

**Comment by thegoldenmule** [comment]
I was mentioning it more to show Brad how he might take what he already has and incrementally learn more Python. That is, my goal was teaching, not widespread support. I would think argparse might be better toward that end.

**Comment by ghost** [comment]
Definitely easier than getopts, thats for sure! 😃

**Comment by bradganley** [comment]
Yeah I'm going to have to dig into that. This is the nerdiest reason I've ever had to want to leave work.
