### ISSUE TITLE
Consider breaking switch statements into functions

### ISSUE THREAD

**Issue by thegoldenmule** [Bradart/firestick-kodi-installer#5]
I'd advise extracting several functions from the main() function. A refactor you could do here is just split out the case statement into functions like:

`case 1: foo()`

**Comment by ghost** [comment]
Any particular reason for this? Speed wise they are about the same. I would have to test both to confirm for sure, but from experience if it ain't broke, don't fix it! xD

**Comment by thegoldenmule** [comment]
Sure, I definitely wasn't mentioning it as a performance suggestion. More functions would most likely be slower, though by a negligible amount.

This suggestion is more about building good habits than about any particular issue with the code (I was also assuming Brad wrote it and wanted tips). Complex switch statements (and by that I mean when each case is pretty long) is often a good indicator of needed refactor. If this were part of an object, then polymorphism would be a good route to take. Since this is just a script, pulling complex pieces out into smaller, more manageable pieces is a good idea. As each of these already pretty long case statements grows over time, you'll be primed to have nice clean code rather than excessively long functions.

**Comment by ghost** [comment]
Makes sense, was just wondering as I code for fun, and not for a living. I'm a systems guy myself. Thanks for the input!
